### PR TITLE
Make `-e` option work with ChiselStage methods

### LINKED ISSUE #1629: One-file-per-module is incompatible with ChiselStage.emit*
The following fails and it shouldn't:

```scala
import chisel3._
import chisel3.stage.ChiselStage

class Foo extends Module {
  val io = IO(new Bundle {
    val in = Input(Bool())
    val out = Output(Bool())
  })

  io.out := ~io.in
}

println((new ChiselStage).emitVerilog(new Foo, Array("-e", "verilog")))
```

This does a `None.get` because the `-e` results in one-file-per-module and the match is narrowly looking for an `EmittedCircuitAnnotation`. 

Change the behavior here so that this works with `-e` by appending the individual emitted modules together.

**Type of issue**: bug report

**Impact**: no functional change

**Development Phase**: proposal

**Other information**
 

https://gitter.im/freechipsproject/chisel3?at=5f90959ca7e77a0ff1602e6e

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

Compile the example above.

**What is the current behavior?**

`None.get` exception.

**What is the expected behavior?**

No match error.

**Please tell us about your environment:**

3.4.0 

**What is the use case for changing the behavior?**

This is an extremely confusing error for an end user...

### PR DESCRIPTION
**Pull request by seldridge**
Prevent a `None.get` where a user passes a `-e` (one-file-per-module) option to one of the `ChiselStage` methods. This was previously checking for the only a circuit, but throwing in `-e` would cause modules to be emitted. Append all the modules together and return this string.

Fixes #1629 

### Contributor Checklist

- [n/a] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [n/a] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- bug fix

#### API Impact

None.

#### Backend Code Generation Impact

None.
#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference.

#### Release Notes

None.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (3.2.x, 3.3.x, 3.4.0, 3.5.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

File: src/test/scala/chiselTests/stage/ChiselStageSpec.scala [hunk 1]
```diff
@@ -40,7 +48,12 @@ class ChiselStageSpec extends AnyFlatSpec with Matchers with Utils {
   behavior of "ChiselStage.emitFirrtl"
 
   it should "return a High FIRRTL string" in {
-    ChiselStage.emitFirrtl(new Foo) should include ("mem bar")
+    ChiselStage.emitFirrtl(new Foo) should include ("mem memory")
+  }
+
+  it should "return a flattened FIRRTL string with '-e high'" in {
+    (new ChiselStage)
+      .emitFirrtl(new Foo, Array("-e", "high", "-td", "test_run_dir/ChiselStageSpec")) should include ("module Bar")
```
Comment (jackkoenig) [inline src/test/scala/chiselTests/stage/ChiselStageSpec.scala:56]: I'd rather this not hardcode `test_run_dir`

Comment (seldridge) [reply src/test/scala/chiselTests/stage/ChiselStageSpec.scala]: Switched to `createTestDirectory`. I've hardcoded this a lot in the past... 😬

Comment (jackkoenig) [reply src/test/scala/chiselTests/stage/ChiselStageSpec.scala]: I'm watching you 🕵️

**Review by jackkoenig — APPROVED** [review]
